<?php

namespace Database\Seeders;

use App\Models\AdminMenu;
use Illuminate\Database\Seeder;

class AdminMenuSeeder extends Seeder
{
    /**
     * 관리자 메뉴 데이터를 시드합니다.
     */
    public function run(): void
    {
        // 기존 데이터 삭제
        AdminMenu::query()->delete();

        // 현재 DB 데이터로 최신화된 메뉴 구성
        $menus = [
            [
                'id' => 1,
                'parent_id' => null,
                'name' => '대시보드',
                'url' => '/backoffice',
                'icon' => 'fa-tachometer-alt',
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-05-05 09:33:08',
                'updated_at' => '2026-03-19 19:58:03',
                'permission_key' => null,
            ],
            [
                'id' => 2,
                'parent_id' => null,
                'name' => '시스템 관리',
                'url' => null,
                'icon' => 'fa-cogs',
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-05-05 09:33:08',
                'updated_at' => '2026-03-19 19:58:03',
                'permission_key' => null,
            ],
            [
                'id' => 3,
                'parent_id' => 6,
                'name' => '기본설정',
                'url' => '/backoffice/setting',
                'icon' => null,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-05-05 09:33:08',
                'updated_at' => '2025-10-07 13:38:54',
                'permission_key' => null,
            ],
            [
                'id' => 4,
                'parent_id' => 2,
                'name' => '메뉴 관리',
                'url' => '/backoffice/admin-menus',
                'icon' => null,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-05-05 09:33:08',
                'updated_at' => '2025-10-09 14:41:00',
                'permission_key' => null,
            ],
            [
                'id' => 6,
                'parent_id' => null,
                'name' => '기본설정',
                'url' => null,
                'icon' => 'fa-file-alt',
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2025-05-05 09:33:08',
                'updated_at' => '2026-03-19 19:58:03',
                'permission_key' => null,
            ],
            [
                'id' => 7,
                'parent_id' => 2,
                'name' => '게시판 관리',
                'url' => '/backoffice/boards',
                'icon' => null,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-05-05 09:33:08',
                'updated_at' => '2025-10-09 14:41:06',
                'permission_key' => null,
            ],
            [
                'id' => 8,
                'parent_id' => 21,
                'name' => '팝업 관리',
                'url' => '/backoffice/popups',
                'icon' => null,
                'order' => 7,
                'is_active' => 1,
                'created_at' => '2025-05-05 09:33:08',
                'updated_at' => '2025-10-07 05:59:49',
                'permission_key' => null,
            ],
            [
                'id' => 9,
                'parent_id' => 2,
                'name' => '게시판 템플릿 관리',
                'url' => '/backoffice/board-templates',
                'icon' => null,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2025-05-06 09:58:14',
                'updated_at' => '2025-10-19 14:11:43',
                'permission_key' => null,
            ],
            [
                'id' => 10,
                'parent_id' => 19,
                'name' => '공지사항',
                'url' => '/backoffice/board-posts/notices',
                'icon' => null,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-05-06 12:44:51',
                'updated_at' => '2026-03-19 17:12:58',
                'permission_key' => null,
            ],
            [
                'id' => 17,
                'parent_id' => 19,
                'name' => 'FAQ',
                'url' => '/backoffice/board-posts/faq',
                'icon' => null,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-08-21 07:20:49',
                'updated_at' => '2026-03-22 19:24:37',
                'permission_key' => null,
            ],
            [
                'id' => 18,
                'parent_id' => 21,
                'name' => '배너 관리',
                'url' => '/backoffice/banners',
                'icon' => null,
                'order' => 2,
                'is_active' => 0,
                'created_at' => '2025-08-24 09:35:23',
                'updated_at' => '2026-04-16 07:19:54',
                'permission_key' => null,
            ],
            [
                'id' => 19,
                'parent_id' => null,
                'name' => '게시판관리',
                'url' => null,
                'icon' => 'fa-chart-bar',
                'order' => 6,
                'is_active' => 1,
                'created_at' => '2025-08-24 09:36:13',
                'updated_at' => '2026-04-28 03:20:44',
                'permission_key' => null,
            ],
            [
                'id' => 20,
                'parent_id' => 6,
                'name' => '관리자 관리',
                'url' => '/backoffice/admins',
                'icon' => null,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-09-19 00:19:49',
                'updated_at' => '2025-10-09 04:28:31',
                'permission_key' => null,
            ],
            [
                'id' => 21,
                'parent_id' => null,
                'name' => '홈페이지관리',
                'url' => null,
                'icon' => 'fa-home',
                'order' => 7,
                'is_active' => 1,
                'created_at' => '2025-09-23 07:20:08',
                'updated_at' => '2026-04-28 03:20:44',
                'permission_key' => null,
            ],
            [
                'id' => 23,
                'parent_id' => 6,
                'name' => '관리자 권한 그룹',
                'url' => '/backoffice/admin-groups',
                'icon' => null,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2025-10-18 01:55:21',
                'updated_at' => '2025-10-18 02:01:41',
                'permission_key' => null,
            ],
            [
                'id' => 39,
                'parent_id' => 6,
                'name' => '카테고리 관리',
                'url' => '/backoffice/categories',
                'icon' => null,
                'order' => 3,
                'is_active' => 0,
                'created_at' => '2025-10-09 01:02:41',
                'updated_at' => '2025-10-18 02:01:41',
                'permission_key' => null,
            ],
            [
                'id' => 41,
                'parent_id' => null,
                'name' => '통계 관리',
                'url' => null,
                'icon' => 'fa-chart-line',
                'order' => 9,
                'is_active' => 1,
                'created_at' => '2025-12-18 08:44:54',
                'updated_at' => '2026-04-28 03:20:49',
                'permission_key' => null,
            ],
            [
                'id' => 42,
                'parent_id' => 41,
                'name' => '접속통계',
                'url' => '/backoffice/access-statistics',
                'icon' => null,
                'order' => 1,
                'is_active' => 1,
                'created_at' => '2025-12-18 08:46:17',
                'updated_at' => '2025-12-18 08:46:27',
                'permission_key' => null,
            ],
            [
                'id' => 43,
                'parent_id' => 41,
                'name' => '사용자 접속로그 목록',
                'url' => '/backoffice/user-access-logs',
                'icon' => null,
                'order' => 2,
                'is_active' => 1,
                'created_at' => '2025-12-18 08:46:51',
                'updated_at' => '2025-12-18 08:47:27',
                'permission_key' => null,
            ],
            [
                'id' => 44,
                'parent_id' => 41,
                'name' => '관리자 접속로그 목록',
                'url' => '/backoffice/admin-access-logs',
                'icon' => null,
                'order' => 3,
                'is_active' => 1,
                'created_at' => '2025-12-18 08:47:05',
                'updated_at' => '2025-12-18 08:47:27',
                'permission_key' => null,
            ],
            [
                'id' => 45,
                'parent_id' => null,
                'name' => '포트폴리오',
                'url' => null,
                'icon' => 'fa-list',
                'order' => 4,
                'is_active' => 1,
                'created_at' => '2026-03-19 19:57:56',
                'updated_at' => '2026-03-22 16:23:17',
                'permission_key' => null,
            ],
            [
                'id' => 46,
                'parent_id' => 21,
                'name' => '출퇴근 관리',
                'url' => '/backoffice/attendance',
                'icon' => null,
                'order' => 3,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'permission_key' => null,
            ],
            [
                'id' => 48,
                'parent_id' => null,
                'name' => '블로그',
                'url' => null,
                'icon' => 'fa-calendar',
                'order' => 5,
                'is_active' => 1,
                'created_at' => '2026-03-23 04:23:31',
                'updated_at' => '2026-03-23 17:05:08',
                'permission_key' => null,
            ],
            [
                'id' => 57,
                'parent_id' => 45,
                'name' => '포트폴리오 관리',
                'url' => '/backoffice/portfolio',
                'icon' => null,
                'order' => 1,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'permission_key' => null,
            ],
            [
                'id' => 58,
                'parent_id' => 48,
                'name' => '블로그 관리',
                'url' => '/backoffice/blog-posts',
                'icon' => null,
                'order' => 1,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'permission_key' => null,
            ],
            [
                'id' => 59,
                'parent_id' => 21,
                'name' => '프로젝트 관리',
                'url' => '/backoffice/project-manages',
                'icon' => null,
                'order' => 1,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'permission_key' => null,
            ],
            [
                'id' => 60,
                'parent_id' => 21,
                'name' => '세금계산서',
                'url' => '/backoffice/intra-tax',
                'icon' => null,
                'order' => 2,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'permission_key' => null,
            ],
            [
                'id' => 53,
                'parent_id' => null,
                'name' => '전자결재',
                'url' => null,
                'icon' => 'fa-calendar',
                'order' => 8,
                'is_active' => 1,
                'created_at' => '2026-04-28 03:20:31',
                'updated_at' => '2026-04-28 03:20:49',
                'permission_key' => null,
            ],
            [
                'id' => 54,
                'parent_id' => 21,
                'name' => '문의 관리',
                'url' => '/backoffice/contacts',
                'icon' => null,
                'order' => 6,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'permission_key' => null,
            ],
            [
                'id' => 55,
                'parent_id' => 53,
                'name' => '전자결재 메인',
                'url' => '/backoffice/approval-main',
                'icon' => null,
                'order' => 1,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'permission_key' => null,
            ],
            [
                'id' => 56,
                'parent_id' => 53,
                'name' => '개인문서함',
                'url' => '/backoffice/approval-personal',
                'icon' => null,
                'order' => 2,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'permission_key' => null,
            ],
            [
                'id' => 49,
                'parent_id' => 53,
                'name' => '결재할 문서함',
                'url' => '/backoffice/approval-pending',
                'icon' => null,
                'order' => 3,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'permission_key' => null,
            ],
            [
                'id' => 50,
                'parent_id' => 53,
                'name' => '협조 문서함',
                'url' => '/backoffice/approval-cooperation',
                'icon' => null,
                'order' => 4,
                'is_active' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'permission_key' => null,
            ],
        ];

        // parent_id가 null인 메뉴들을 먼저 생성
        $parentMenus = array_filter($menus, function ($menu) {
            return $menu['parent_id'] === null;
        });

        foreach ($parentMenus as $menu) {
            AdminMenu::forceCreate($menu);
        }

        // 그 다음에 자식 메뉴들을 생성
        $childMenus = array_filter($menus, function ($menu) {
            return $menu['parent_id'] !== null;
        });

        foreach ($childMenus as $menu) {
            AdminMenu::forceCreate($menu);
        }
    }
}
